### PR TITLE
fix: multiple typo's

### PR DESCRIPTION
**Pull request by fgierlinger**
* fix: typo pull_up_dowm to pull_up_down
* docs: fix typo in setup description

### CODE REVIEW

**Comment by codenio** [comment]
thanks for this.
could you please add up all typos in this same PR..? (in case of any)

**Comment by fgierlinger** [comment]
of course, I just didn't see those yesterday when I made the change for the import statement.

**Comment by codenio** [comment]
that was wonderful. seems like I had just focused only on functionality/working :sweat_smile: .
thanks for this. all done..? can this be merged.

**Comment by fgierlinger** [comment]
That's it.

**Pull request merged**
